version: "3.9"

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: ["bash", "-c", "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: ["bash", "-c", "npm install && npm run dev -- --host 0.0.0.0"]
