version: "3.9"

services:
  backend:
    build: ./backend
    env_file:
      - .env   # points to the .env in repo root
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
