services:
  - type: web
    name: astro-quant-live-backend
    env: python
    plan: free
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend
      uvicorn server:app --host 0.0.0.0 --port $PORT --workers 2 --loop uvloop
    envVars:
      - key: AQ_DB_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: ALERT_EMAILS
        sync: false

  - type: web
    name: astro-quant-live-frontend
    env: static
    plan: free
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    buildCommand: |
      cd frontend
      if [ -f yarn.lock ]; then yarn install; else npm install; fi
      npm run build || yarn build
    publishDir: frontend/build
