services:
  - type: web
    name: astro-quant-live-backend
    env: python
    plan: free
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 2 --threads 2

static_sites:
  - name: astro-quant-live-frontend
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    publishDirectory: public
    buildCommand: ""
