services:
  - type: web
    name: astro-quant-live-backend
    env: python
    plan: free
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend
      uvicorn server:app --host 0.0.0.0 --port $PORT --workers 2 --loop uvloop
