services:
  - type: web
    name: astro-quant-live-backend
    env: python
    plan: free
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend
      uvicorn server:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: AQ_DB_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  - type: web
    name: astro-quant-live-frontend
    env: node
    plan: free
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    buildCommand: |
      # no compile/build step required for simple static frontend
      # install small static server
      npm i -g serve
    startCommand: |
      # serve the frontend directory directly
      cd frontend
      serve -s . -l $PORT
