services:
  - type: web
    name: astro-quant-live-backend
    env: python
    plan: free
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r backend/requirements.txt
    startCommand: |
      cd backend
      uvicorn server:app --host 0.0.0.0 --port $PORT --workers 2 --loop uvloop

  - type: static_site
    name: astro-quant-live-frontend
    repo: SRAVANTAMARANA/astro-quant-live
    branch: main
    buildCommand: |
      cd frontend
      if [ -f yarn.lock ]; then yarn install; else npm install; fi
      npm run build || yarn build
    publishDir: frontend/build
