services:
  - type: web
    name: astro-quant-live-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.server:app --host 0.0.0.0 --port $PORT
    branch: main
    repo: https://github.com/SRAVANTAMARANA/astro-quant-live

  - type: web
    name: astro-quant-live-frontend
    env: node
    plan: free
    buildCommand: |
      cd frontend
      if [ -f yarn.lock ]; then yarn install; else npm install; fi
      npm run build || yarn build
    startCommand: |
      cd frontend
      npx serve -s build -l $PORT
    branch: main
    repo: https://github.com/SRAVANTAMARANA/astro-quant-live
